@startuml
actor View as F
participant ThymeleafEngine as T
participant Service as S
participant Database as DB

F -> S: GET /accounts/{id}
S -> DB: get account by id
DB --> S: Account
alt account does not exist
    S -> S: throw error
    S --> T: error page
    T --> F: error page
end
S --> T: 200 OK
note left
{
    account: {
        accountNumber: some-uuid
        name: some name
        email: some@email.com
        openingAmount: 50.0
    }
}
end note
T --> F: render account page
@enduml
