@startuml
actor View as F
participant ThymeleafEngine as T
participant Service as S
participant Database as DB

F -> S: POST /accounts
note right
{
    name: some name
    email: some@email.com
    openingAmount: 50.0
}
end note
S -> DB: get account by email adress and name
DB --> S: Optional<Account>
alt account exists
    S -> S: throw error
    S --> T: error page
    T --> F: error page
else new account
S -> DB: save account
DB --> S: accountNumber
S --> T: redirect /accounts/{accountNumber}
T -> T: get  accounts detail page
T --> F: render accounts detail page
end
@enduml
